os:
  - linux

language: go

go:
    - 1.7

install: true

before_install:
  - make deps

#- go vet ./...
script:
  - go test ./... -v

cache:
    directories:
        - $GOPATH/src/gx

notifications:
  email: false
